name: Check PR File Changes

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Count changed files
        id: count_files
        run: |
          echo "Changed files:"
          git diff --name-status ${{ github.event.before }} ${{ github.sha }} | wc -l > count.txt
          echo "::set-output name=count::$(cat count.txt)"
      
      - name: Post a comment if PR exceeds 15 files
        if: env.PR_FILES > 15
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --body "This PR contains **${{ env.PR_FILES }}** files, which is more than the allowed limit of 15 files. Please split it into smaller PRs for easier review."

      - name: Fail if more than 15 files changed
        run: |
          if [ "${{ steps.count_files.outputs.count }}" -gt 15 ]; then
            echo "Error: More than 15 files changed in the PR!"
            exit 1
          fi
