name: Check Changed Files

on:
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  count_changed_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 1000

      - name: Fetch main branch
        run: git fetch origin main

      - name: Count changed files
        id: count
        run: |
          # Get the number of changed files
          FILES_CHANGED=$(git diff --name-only origin/main... | wc -l)
          echo "Changed files: $FILES_CHANGED"

          NON_INTERFACE_FILES=$(echo "$CHANGED_FILES" | grep -vE '^I' | wc -l)

          # Set the output variable
          echo "PR_FILES=$NON_INTERFACE_FILES" >> $GITHUB_ENV
      
      - name: Fail if more than 15 files changed
        run: |
          if [ ${{ env.PR_FILES }} -gt 15 ]; then
            echo "Error: More than 15 files changed in this PR. Please limit to 15 files or fewer."
            exit 1
          fi
